### ISSUE TITLE
ShadowsocksX Menu workflow keyword "sss" 后所有命令均无反应

### ISSUE THREAD

**Issue by gdshen** [onestark/alfred-workflows#1]
使用OS X 10.11.6, Alfred 3.03版本

**Comment by Teraflopst** [comment]
@gdshen95 可能会有一点延迟，但是我使用是可以的。你先试一下用鼠标点击一下 Menubar 的小飞机图标，再试试 Alfred。

我使用 **OS X 10.11.3**，**Alfred 3.01**

**Comment by gdshen** [comment]
@onestark 刚在Accessibility里面添加了alfred 3，现在可以用了，多谢。
